esphome:
  name: heizung
  friendly_name: heizung

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_passwort

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_heizung_fallback_ssid
    password: !secret wifi_heizung_fallback_password

captive_portal:

one_wire:
 - id: bus_one
   platform: gpio
   pin:
    number: D4
    mode:
      input: true
      pullup: true

# Individual sensors
sensor:
  - platform: dallas_temp
    address: 0xcf000000382ca028
    name: "Vorlauf HK1"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-plus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
  - platform: dallas_temp
    address: 0x68000000342c1628
    name: "Rücklauf HK1"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-minus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s

    